dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
  
sudo: false

cache:
  directories:
    - $HOME/.m2
    
# use latest java version available instead of travis default
addons:
  sonarcloud:
    organization: "eventstorm-projects"
    token:
      secure: $SONAR_TOKEN
      
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pcoverage -Dmaven.javadoc.skip=true -Dgpg.skip=true