dist: xenial
language: java
sudo: false

addons:
  sonarcloud:
    organization: "eventstorm-projects"
    token:
      secure: $SONAR_TOKEN
      
jdk:
  - openjdk8
  
git:
  depth: false

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - sonar-scanner -Dsonar.verbose=true -X -Dsonar.projectKey=eu.eventstorm:eventstorm -Dsonar.login=$SONAR_TOKEN