dist: xenial
language: java
sudo: false
addons:
  sonarcloud:
    organization: eventstorm-projects
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dmaven.javadoc.skip=true -Dgpg.skip=true