dist: xenial
language: java
sudo: false

addons:
  sonarcloud:
    organization: eventstorm-projects
    token:
      secure: ${SONAR_TOKEN}

jdk:
  - openjdk8
  
git:
  depth: false

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - sonar-scanner -Dsonar.verbose=true -X