package eu.eventstorm.sql.apt.flyway;

import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.Timestamp;

import eu.eventstorm.sql.apt.log.LoggerFactory;
import eu.eventstorm.sql.annotation.Column;
import eu.eventstorm.sql.annotation.PrimaryKey;
import eu.eventstorm.sql.type.Json;

/**
 * @author <a href="mailto:jacques.militello@gmail.com">Jacques Militello</a>
 * 
 * https://docs.oracle.com/cd/E19501-01/819-3659/gcmaz/
 */
final class FlywayDialectOracle implements FlywayDialect {

	static final FlywayDialect INSTANCE = new FlywayDialectOracle();

	@Override
	public String toSqlType(String javaType, PrimaryKey column) {
		

		if (int.class.getName().equals(javaType) || Integer.class.getName().equals(javaType)) {
			return "NUMBER(10)";
		}

		if (long.class.getName().equals(javaType) || Long.class.getName().equals(javaType)) {
			return "NUMBER(19)";
		}
		
		if (String.class.getName().equals(javaType)) {
			return "VARCHAR2(" + column.length() + ")";
		}
		
		LoggerFactory.getInstance().getLogger(FlywayDialectOracle.class).error("No sql type for java type (PrimaryKey) [" + javaType + "]");
		return null;
	}
	
	@Override
	public String toSqlType(String javaType, Column column) {

		if (int.class.getName().equals(javaType) || Integer.class.getName().equals(javaType)) {
			return "NUMBER(10)";
		}

		if (long.class.getName().equals(javaType) || Long.class.getName().equals(javaType)) {
			return "NUMBER(19)";
		}

		if (byte.class.getName().equals(javaType) || Byte.class.getName().equals(javaType)) {
			return "NUMBER(3)";
		}
		
		if (boolean.class.getName().equals(javaType) || Boolean.class.getName().equals(javaType)) {
			return "NUMBER(1)";
		}
		
		if (String.class.getName().equals(javaType)) {
			return "VARCHAR2(" + column.length() + ")";
		}

		if (Timestamp.class.getName().equals(javaType)) {
			return "TIMESTAMP WITH TIME ZONE";
		}
		
		if (Date.class.getName().equals(javaType)) {
			return "DATE";
		}
		
		if (double.class.getName().equals(javaType) || Double.class.getName().equals(javaType)) {
			return "NUMBER(19,4)";
		}

		if (float.class.getName().equals(javaType) || Float.class.getName().equals(javaType)) {
			return "NUMBER(19,4)";
		}
		
		if (Json.class.getName().equals(javaType)) {
			if (column.length() != 255) {
				return "VARCHAR2(" + column.length() + ")";
			} else {
				return "CLOB";
			}
		}
		
		if (Blob.class.getName().equals(javaType) || "byte[]".equals(javaType)) {
			return "BLOB";
		}
		
		if (Clob.class.getName().equals(javaType)) {
			return "CLOB";
		}
		
		LoggerFactory.getInstance().getLogger(FlywayDialectOracle.class).error("No sql type for java type [" + javaType + "]");
		return null;
	}

	@Override
	public String wrap(String value) {
		return value;
	}

	/**
	 * https://chartio.com/resources/tutorials/how-to-define-an-auto-increment-primary-key-in-oracle/
	 */
	@Override
	public String autoIncrementType(String javaType) {

		if (int.class.getName().equals(javaType) || Integer.class.getName().equals(javaType)) {
			return "NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY";
		}

		if (long.class.getName().equals(javaType) || Long.class.getName().equals(javaType)) {
			return "NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY";
		}

		LoggerFactory.getInstance().getLogger(FlywayDialectOracle.class).error("No sql AUTO INCREMENT type for java type [" + javaType + "]");

		return null;
	}
}
